-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Nov 30, 2019 at 01:51 PM
-- Server version: 10.3.15-MariaDB
-- PHP Version: 7.1.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `autoserved`
--

-- --------------------------------------------------------

--
-- Table structure for table `masterlist_pms`
--

-- CREATE TABLE `masterlist_pms` (
--   `id` bigint(20) UNSIGNED NOT NULL,
--   `mileage` int(11) NOT NULL,
--   `check_items` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `clean_items` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL,
--   `change_items` longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `masterlist_pms`
--

INSERT INTO `masterlist_pms` (`id`, `mileage`, `check_items`, `clean_items`, `change_items`) VALUES
(1, 5000, '[\"All Lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"EGR System, EGR valve and intake manifold\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\",\"Air Cleaner element\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(2, 10000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Check EGR System, EGR valve and intake manifold\",\"Transmission gear oil every 30,000km (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\",\"Air Cleaner element\"]', '[\"Replace Oil Filter\",\"Engine Oil\"]'),
(3, 15000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Check Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\"]', '[\"EGR System, EGR valve and intake manifold Every\",\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(4, 20000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir and change every\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Condition of intake air, radiator hoses (connection of clamps)\",\"Check Valve clearance (except for vehicles with auto lash adjusters)\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Exhaust system for leaks\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Spark plugs (If Equipped)\",\"Fuel Filter\",\"Fuel Filter No. 2 (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]'),
(5, 25000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\",\"EGR System, EGR valve and intake manifold\",\"Reset PMS Reminder (For models equipped)\"]', '[\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Oil Filter\",\"Engine Oil\"]'),
(6, 30000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Front and rear wheel bearings for play, humming noise and repack bearing\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"EGR System, EGR valve and intake manifold\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Oil Filter\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Engine Oil\"]'),
(7, 35000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir and change\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir every\",\"EGR System, EGR valve and intake manifold\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(8, 40000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Radiator cap sticker if intact. Replace if damaged\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Condition of intake air, radiator hoses (connection of clamps)\",\"Valve clearance (except for vehicles with auto lash adjusters)\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Exhaust system for leaks\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Engine Coolant\",\"Brake Fluid, Clutch Fluid\",\"Power Steering Fluid\",\"Spark plugs (If Equipped)\",\"Fuel Filter\",\"Fuel Filter No. 2 (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]'),
(9, 45000, '[\"All lights\",\"Horn\",\"Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"EGR System, EGR valve and intake manifold\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Air Cleaner element\",\"Replace Oil Filter\",\"Engine Oil\"]'),
(10, 50000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Front and rear wheel bearings for play, humming noise and repack bearing\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]'),
(11, 55000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\",\"EGR System, EGR valve and intake manifold\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(12, 60000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Condition of intake air, radiator hoses (connection of clamps)\",\"Valve clearance (except for vehicles with auto lash adjusters)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Exhaust system for leaks\",\"Front and rear wheel bearings for play, humming noise and repack bearing\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"EGR System, EGR valve and intake manifold\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Timing belt (If Equipped)\",\"Spark plugs (If Equipped)\",\"Fuel Filter\",\"Fuel Filter No. 2 (If Equipped)\",\"Oil Filter\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil every (SUV/AUV/PICK-UP/VAN)\",\"Engine Oil\"]'),
(13, 65000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\",\"EGR System, EGR valve and intake manifold\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Air Cleaner element\",\"Oil Filter\",\"Engine Oil\"]'),
(14, 70000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir every 5,000km and change every 40,000km\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\",\"A/C Cabin Filter (If Equipped)\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(15, 75000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\"]', '[\"Air Cleaner element\",\"EGR System, EGR valve and intake manifold\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]'),
(16, 80000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Radiator cap sticker if intact. Replace if damaged\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Condition of intake air, radiator hoses (connection of clamps)\",\"Valve clearance (except for vehicles with auto lash adjusters)\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Exhaust system for leaks\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment (Starting at 15,000km)\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Engine Coolant\",\"Brake Fluid, Clutch Fluid\",\"Steering Fluid\",\"Timing belt (If Equipped)\",\"Spark plugs (If Equipped)\",\"Fuel Filter\",\"Fuel Filter No. 2 (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]'),
(17, 85000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\",\"EGR System, EGR valve and intake manifold\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Air Cleaner element\",\"Oil Filter\",\"Engine Oil\"]'),
(18, 90000, '[\"A/C Cooling and Performance\",\"All lights\",\"Battery health using battery tester\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Engine coolant level reservoir\",\"Engine idling speed\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Fluid level in brake, clutch and power steering reservoir\",\"Front and rear wheel bearings for play, humming noise\",\"Horn\",\"Radiator cap sticker if intact. Replace if damaged\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Wheel alignment (Starting at 15,000km)\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\"]', '[\"EGR System, EGR valve and intake manifold\",\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\",\"A/C Cabin Filter (If Equipped)\"]', '[\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"Oil Filter\",\"Engine Oil\"]'),
(19, 95000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"EGR System, EGR valve and intake manifold\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Wheel alignment\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Air Cleaner element\",\"Check Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"Oil Filter\",\"Engine Oil\"]'),
(20, 100000, '[\"All lights\",\"Horn\",\"A/C Cooling and Performance\",\"Wiper blade Condition and wiper washer spray operation and washer fluid\",\"Brake pedal free-play and parking brake lever stroke\",\"Clutch pedal free-play (If Manual Transmission Vehicle)\",\"Reset PMS Reminder (For models equipped)\",\"Battery health using battery tester\",\"Engine coolant level reservoir\",\"Radiator cap sticker if intact. Replace if damaged\",\"Fluid level in brake, clutch and power steering reservoir\",\"Drive belts for cracks fraying and wear. Adjust tension as needed\",\"Condition of intake air, radiator hoses (connection of clamps)\",\"Valve clearance (except for vehicles with auto lash adjusters)\",\"EGR System, EGR valve and intake manifold\",\"Transmission gear oil (For Manual Transmission Vehicle)\",\"ATF/CVT Fluid (For Automatic Transmission Vehicle)\",\"Differential gear oil (SUV/AUV/PICK-UP/VAN)\",\"Drive shaft and steering linkage condition and connections (including seals and boots)\",\"Suspension system including ball joints, and dust cover for damage, looseness and play. Lubricate grease fittings if applicable\",\"Exhaust system for leaks\",\"Front and rear wheel bearings for play, humming noise\",\"Brake/fuel hoses and pipes (and clamps) for leakage and deterioration\",\"Engine, transmission, and front and rear axle housings for any sign of coolant or oil leak\",\"Engine idling speed\",\"Condition of tires (Foreign objects, presence, pressure and wear depth)\",\"Rotate tires and reset Tire pressure monitoring system (TPMS) Note : Follow rotation pattern specified for each tire type\",\"Wheel alignment\"]', '[\"Air Cleaner element\",\"Brake Disc and Pads, Including Shoe Linings and drums (drum disc) for wear\"]', '[\"A/C Cabin Filter (If Equipped)\",\"Timing belt (If Equipped)\",\"Spark plugs (If Equipped)\",\"Fuel Filter\",\"Fuel Filter No. 2 (If Equipped)\",\"Oil Filter\",\"Engine Oil\"]');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `masterlist_pms`
--
ALTER TABLE `masterlist_pms`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `masterlist_pms`
--
ALTER TABLE `masterlist_pms`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
