export const TOGGLE_SIDEBAR_MENU = "navigation/TOGGLE_SIDEBAR_MENU";
export const TOGGLE_DROPDOWN_MENU = "navigation/TOGGLE_DROPDOWN_MENU";
export const GET_IN_APP_NOTIFICATIONS = "navigation/GET_IN_APP_NOTIFICATIONS";
export const GET_ALL_APP_NOTIFICATIONS = "navigation/GET_ALL_APP_NOTIFICATIONS";
export const SET_FIRST_TIME_LOGIN = "navigation/SET_FIRST_TIME_LOGIN";
export const READ_ALL_APP_NOTIFICATIONS =
  "navigation/READ_ALL_APP_NOTIFICATIONS";
